language: node_js
node_js:
- '8'
install:
- yarn install
- yarn build
deploy:
  provider : heroku
  api_key:
    secure: Q3ZW/v/CV0odCrX3JTrMPJaoYA+uaoGIWkTsA/4sG2PFCv2mLnA6wgPp54Py06D0TPxmCHzagzC55MVlV3M4IbmpQSaoagRIVoJbXwNd6/dUvjhFhpHXqpNG+QvwMaNB6ULA+m/ZK8s1AteYkIWJOSbDvgSJLkjDJ9B15LsPHCWflQHkX+ngrg7QjMVG96COTwRKurWQRf2AYM/We3irtwSITwGxydGg3If1YFZrmKYB2rXAl5aXkuvKUHdmEfwrUjeP+sgAsqh5qlnasDxjlUJgZoU0FEaUhqctz9aYwj89nkIdnKNN0xbHyB4B+cWYeOeetQQSlwc1CVeJSPP3JOw6mP+2IQvebqYkOIM2BGLxsztkVvgQV+ni5BP0tfKK0aySkLTcUA/Qlh2Nw5YC+EF524nwlwFnvh7fM23N01ChNFGHCCJ89xAeY8+8hA2U1+MXAEnZxDkfz5lSAC57nzAbyoBgOB4xzumt2z7tOGV64ekR2InWNieK423JAjs6uuL2kOE9XPLSsCtGWIP50SDlJzIG3pDx61OFGL2hVFyJLRXdE8Gdo2joBCRVXrxma3vuC9JEjN5aQ+r5LUQ+G6RobXx8v19smGHdNxRHKHTKEnNg9IRkQCLoeAYtUJJwi5qy+lH2SADH+6KLNGx40tk9L1xdprssCRjiG3EHq+0=
  app: expts-grph-react-travis